version: "3.7"
services:
 rserve:
   image: swipl/rserve
   network_mode: "none"
   volumes:
      - rserve-volume:/rserve
 websocket-bridge:
   image: veupathdb/rserve
   entrypoint: "/usr/local/lib/R/site-library/Rserve/libs/forward"
   command: ["-w", "2376", "-s", "/rserve/socket"]
   stdin_open: true
   tty: true
   network_mode: "bridge"
   volumes:
     - rserve-volume:/rserve
   ports:
     - "2376:2376"s
      
volumes:
  rserve-volume:
